{
  "model":
    {
      "name": "default",
      "type": "gpt",
      "d_embed": 1024,
      "n_layers": 8,
      "n_heads": 16,
      "max_seq_len": 512,
      "dropout": 0.1,
    },
  "dataset": "slim-pajama",
}
